language: node_js
node_js:
  - "lts"

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t fivefullsummers/docker-react .

script:
  - docker run -e CI=true fivefullsummers/docker-react npm run test